version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senhateste123
      POSTGRES_USER: TesteInatel
      POSTGRES_DB: BANCO_PADRAO

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081